apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rancher-demo
  template:
    metadata:
      labels:
        app: rancher-demo
    spec:
      containers:
        - name: rancher-demo
          image: grahamh/rancher-demo:1.2
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: web
            protocol: TCP
          env:
            - name: CONTAINER_COLOR
              value: black
          readinessProbe:
            httpGet:
              port: web
              path: /
