apiVersion: v1
kind: Service
metadata:
  name: rancher-demo-np
  namespace: default
spec:
  type: NodePort
  selector:
    app: rancher-demo
  ports:
    - name: web
      port: 80
      targetPort: web
      nodePort: 30010
